# Data normalization and Data Type Conversion
## Vishvam Delwadiya
## PRN: - 25070123124

In [ ]:
#Dataset

import pandas as pd
import numpy as np

data = {
    'Product':['Laptop','Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000,20000,30000,2000,8000,45000],
    'Units_Sold': [25,60,35,80,50,15],
    'Discount': [10,15,12,20,18,8]
}
df = pd.DataFrame(data)
print(df)
df

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [ ]:
#1. Min-Max Normalization
# Min-Max Normalization for Price

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print(df)
df

#if to print only specific column --> print(df[['Product','Price','Price_MinMax']])

      Product  Price  Units_Sold  Discount  Price_MinMax
0      Laptop  55000          25        10      1.000000
1      Mobile  20000          60        15      0.339623
2      Tablet  30000          35        12      0.528302
3  Headphones   2000          80        20      0.000000
4  Smartwatch   8000          50        18      0.113208
5      Camera  45000          15         8      0.811321

      Product  Price  Units_Sold  Discount  Price_MinMax
0      Laptop  55000          25        10      1.000000
1      Mobile  20000          60        15      0.339623
2      Tablet  30000          35        12      0.528302
3  Headphones   2000          80        20      0.000000
4  Smartwatch   8000          50        18      0.113208
5      Camera  45000          15         8      0.811321

In [ ]:
#2. Z-score Normalization
df['Units_Zscore'] = (df['Unit_Sold'] - df['Unit_Sold'].mean)

In [ ]:
#Normalization Multiple columns
cols = ['Price', 'Units_Sold','Discount']

df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
df_norm

      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [ ]:
#2.Z-score Normalization
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
print(df[['Product', 'Units_Sold', 'Units_Zscore']])

      Product  Units_Sold  Units_Zscore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [ ]:
#3. Decimal scaling

df['Price_Decimal'] = df['Price'] / 100000

print(df[['Product', 'Price', 'Price_Decimal']])

      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

In [ ]:
# Data Encoding


import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}

df1 = pd.DataFrame(data)

print(df1)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value
0         4500
1         2300
2         3200
3         5200
4         1800
5         4100

In [ ]:
#Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df1['Gender_Label'] = le.fit_transform(df1['Customer_Gender'])

df1

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label
0,101,Male,UPI,Electronics,Pune,4500,1
1,102,Female,Credit Card,Clothing,Mumbai,2300,0
2,103,Female,Debit Card,Home,Delhi,3200,0
3,104,Male,COD,Electronics,Bangalore,5200,1
4,105,Female,UPI,Beauty,Pune,1800,0
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1

In [ ]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df1['City_Label'] = le.fit_transform(df1['City'])

df1

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3
2,103,Female,Debit Card,Home,Delhi,3200,0,1
3,104,Male,COD,Electronics,Bangalore,5200,1,0
4,105,Female,UPI,Beauty,Pune,1800,0,4
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2

In [ ]:
#Method 2: One-hot Encoding

df_encoded1 = pd.get_dummies(df1,columns=['Customer_Gender'])
print(df_encoded1)

   Order_ID Payment_Method Product_Category       City  Order_Value  \
0       101            UPI      Electronics       Pune         4500
1       102    Credit Card         Clothing     Mumbai         2300
2       103     Debit Card             Home      Delhi         3200
3       104            COD      Electronics  Bangalore         5200
4       105            UPI           Beauty       Pune         1800
5       106     Debit Card      Electronics  Hyderabad         4100

   Gender_Label  City_Label  Customer_Gender_Female  Customer_Gender_Male
0             1           4                   False                  True
1             0           3                    True                 False
2             0           1                    True                 False
3             1           0                   False                  True
4             0           4                    True                 False
5             1           2                   False                  True

In [ ]:
#Method 3: Dummy Encoding (Drop First)
df_dummy = pd.get_dummies(df1, columns=['Payment_Method'], drop_first=True)

print(df_dummy)

   Order_ID Customer_Gender Product_Category       City  Order_Value  \
0       101            Male      Electronics       Pune         4500
1       102          Female         Clothing     Mumbai         2300
2       103          Female             Home      Delhi         3200
3       104            Male      Electronics  Bangalore         5200
4       105          Female           Beauty       Pune         1800
5       106            Male      Electronics  Hyderabad         4100

   Gender_Label  City_Label  Payment_Method_Credit Card  \
0             1           4                       False
1             0           3                        True
2             0           1                       False
3             1           0                       False
4             0           4                       False
5             1           2                       False

   Payment_Method_Debit Card  Payment_Method_UPI
0                      False                True
1                      False               False
2                       True               False
3                      False               False
4                      False                True
5                       True               False

In [ ]:
# Amazon data set

In [2]:
import pandas as pd
import numpy as np

# Load the Amazon dataset
df = pd.read_csv('amazon_products_dataset_Expt-14.csv')
print(df.head())

  Product_ID       Product_Name  Price  Rating  Reviews  Units_Sold
0       P101     Wireless Mouse    799     4.3     1520         350
1       P102  Bluetooth Speaker   1499     4.5      980         220
2       P103       USB Keyboard    699     4.1      870         180
3       P104     Gaming Headset   2499     4.6     2100         410
4       P105         Smartwatch   3999     4.4     3050         520

In [3]:
# Min-Max Normalization for Price
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print(df[['Product_Name', 'Price', 'Price_MinMax']].head())

        Product_Name  Price  Price_MinMax
0     Wireless Mouse    799      0.020243
1  Bluetooth Speaker   1499      0.048583
2       USB Keyboard    699      0.016194
3     Gaming Headset   2499      0.089069
4         Smartwatch   3999      0.149798

In [4]:
# Z-score Normalization for Units_Sold
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()

print(df[['Product_Name', 'Units_Sold', 'Units_Zscore']].head())

        Product_Name  Units_Sold  Units_Zscore
0     Wireless Mouse         350      0.812282
1  Bluetooth Speaker         220     -0.260855
2       USB Keyboard         180     -0.591051
3     Gaming Headset         410      1.307576
4         Smartwatch         520      2.215615

In [5]:
# Normalization for Multiple columns
cols = ['Price', 'Rating', 'Reviews', 'Units_Sold']

df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print(df_norm.head())

      Price    Rating   Reviews  Units_Sold
0  0.020243  0.428571  0.291005    0.518519
1  0.048583  0.714286  0.148148    0.277778
2  0.016194  0.142857  0.119048    0.203704
3  0.089069  0.857143  0.444444    0.629630
4  0.149798  0.571429  0.695767    0.833333

In [6]:
# Decimal scaling for Reviews (Dividing by 10,000 as the reviews are mostly in thousands/hundreds)
df['Reviews_Decimal'] = df['Reviews'] / 10000

print(df[['Product_Name', 'Reviews', 'Reviews_Decimal']].head())

        Product_Name  Reviews  Reviews_Decimal
0     Wireless Mouse     1520            0.152
1  Bluetooth Speaker      980            0.098
2       USB Keyboard      870            0.087
3     Gaming Headset     2100            0.210
4         Smartwatch     3050            0.305

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Applying Label Encoding on Product_Name
df['Product_Name_Label'] = le.fit_transform(df['Product_Name'])

print(df[['Product_Name', 'Product_Name_Label']].head())

        Product_Name  Product_Name_Label
0     Wireless Mouse                  48
1  Bluetooth Speaker                   3
2       USB Keyboard                  42
3     Gaming Headset                  10
4         Smartwatch                  36

In [8]:
# One-hot Encoding on Product_Name
# Note: Since all 50 products are unique, this will create 50 new dummy columns.
df_encoded = pd.get_dummies(df, columns=['Product_Name'])

print(df_encoded.head())

  Product_ID  Price  Rating  Reviews  Units_Sold  Price_MinMax  Units_Zscore  \
0       P101    799     4.3     1520         350      0.020243      0.812282
1       P102   1499     4.5      980         220      0.048583     -0.260855
2       P103    699     4.1      870         180      0.016194     -0.591051
3       P104   2499     4.6     2100         410      0.089069      1.307576
4       P105   3999     4.4     3050         520      0.149798      2.215615

   Reviews_Decimal  Product_Name_Label  Product_Name_Action Camera  ...  \
0            0.152                  48                       False  ...
1            0.098                   3                       False  ...
2            0.087                  42                       False  ...
3            0.210                  10                       False  ...
4            0.305                  36                       False  ...

   Product_Name_USB Flash Drive  Product_Name_USB Hub  \
0                         False                 False
1                         False                 False
2                         False                 False
3                         False                 False
4                         False                 False

   Product_Name_USB Keyboard  Product_Name_VR Headset  Product_Name_Webcam  \
0                      False                    False                False
1                      False                    False                False
2                       True                    False                False
3                      False                    False                False
4                      False                    False                False

   Product_Name_WiFi Router  Product_Name_Wireless Charger  \
0                     False                          False
1                     False                          False
2                     False                          False
3                     False                          False
4                     False                          False

   Product_Name_Wireless Keyboard  Product_Name_Wireless Mouse  \
0                           False                         True
1                           False                        False
2                           False                        False
3                           False                        False
4                           False                        False

   Product_Name_Wireless Presenter
0                            False
1                            False
2                            False
3                            False
4                            False

[5 rows x 59 columns]

In [9]:
# Dummy Encoding (Drop First) to prevent the dummy variable trap
df_dummy = pd.get_dummies(df, columns=['Product_Name'], drop_first=True)

print(df_dummy.head())

  Product_ID  Price  Rating  Reviews  Units_Sold  Price_MinMax  Units_Zscore  \
0       P101    799     4.3     1520         350      0.020243      0.812282
1       P102   1499     4.5      980         220      0.048583     -0.260855
2       P103    699     4.1      870         180      0.016194     -0.591051
3       P104   2499     4.6     2100         410      0.089069      1.307576
4       P105   3999     4.4     3050         520      0.149798      2.215615

   Reviews_Decimal  Product_Name_Label  Product_Name_Air Fryer  ...  \
0            0.152                  48                   False  ...
1            0.098                   3                   False  ...
2            0.087                  42                   False  ...
3            0.210                  10                   False  ...
4            0.305                  36                   False  ...

   Product_Name_USB Flash Drive  Product_Name_USB Hub  \
0                         False                 False
1                         False                 False
2                         False                 False
3                         False                 False
4                         False                 False

   Product_Name_USB Keyboard  Product_Name_VR Headset  Product_Name_Webcam  \
0                      False                    False                False
1                      False                    False                False
2                       True                    False                False
3                      False                    False                False
4                      False                    False                False

   Product_Name_WiFi Router  Product_Name_Wireless Charger  \
0                     False                          False
1                     False                          False
2                     False                          False
3                     False                          False
4                     False                          False

   Product_Name_Wireless Keyboard  Product_Name_Wireless Mouse  \
0                           False                         True
1                           False                        False
2                           False                        False
3                           False                        False
4                           False                        False

   Product_Name_Wireless Presenter
0                            False
1                            False
2                            False
3                            False
4                            False

[5 rows x 58 columns]